'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
type Schedule = { id:string; title:string; start:string; end:string; category:string; color:string; note?:string; done?:boolean; repeat?:{ weekdays:number[]; until:string } };
type Task = { id:string; title:string; bucket:'inbox'|'week'; priority:1|2|3; dueDate?:string; done?:boolean };
const colors:Record<string,string>={집중:'#6658d3',공부:'#3478c8',건강:'#31856c',생활:'#c66b3d'};
const backgrounds:Record<string,string>={집중:'#6658d3',공부:'#3478c8',건강:'#31856c',생활:'#c66b3d'};
const hours=Array.from({length:18},(_,i)=>i+6), weekdays=['월','화','수','목','금','토','일'];
const pad=(n:number)=>String(n).padStart(2,'0');
const dateKey=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const mins=(time:string)=>{const[h,m]=time.split(':').map(Number);return h*60+m};
const sameDay=(a:Date,b:Date)=>dateKey(a)===dateKey(b);
const mondayOf=(date:Date)=>{const d=new Date(date),day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d};
const addDays=(date:Date,n:number)=>{const d=new Date(date);d.setDate(d.getDate()+n);return d};
const starter:Schedule[]=[
 {id:'sample-1',title:'오늘의 계획 정리',start:'08:00',end:'09:00',category:'생활',color:colors.생활},
 {id:'sample-2',title:'알고리즘 공부',start:'10:00',end:'12:00',category:'공부',color:colors.공부},
 {id:'sample-3',title:'점심 & 산책',start:'12:30',end:'13:30',category:'건강',color:colors.건강},
 {id:'sample-4',title:'프로젝트 몰입',start:'15:00',end:'17:00',category:'집중',color:colors.집중},
];
const starterTasks:Task[]=[
 {id:'task-1',title:'공학작문 및 발표 과제',bucket:'week',priority:1},
 {id:'task-2',title:'출석인정서 발급',bucket:'week',priority:1,dueDate:dateKey(addDays(mondayOf(new Date()),4))},
 {id:'task-3',title:'양말 구매',bucket:'inbox',priority:3},
 {id:'task-4',title:'리눅스마스터 공부',bucket:'week',priority:2},
];

export default function Home(){
 const[weekStart,setWeekStart]=useState(()=>mondayOf(new Date()));
 const[itemsByDate,setItemsByDate]=useState<Record<string,Schedule[]>>({});
 const[ready,setReady]=useState(false),[modalOpen,setModalOpen]=useState(false);
 const[tasks,setTasks]=useState<Task[]>([]),[quickTask,setQuickTask]=useState('');
 const[agendaOpen,setAgendaOpen]=useState(true);
 const[editing,setEditing]=useState<Schedule|null>(null),[targetDate,setTargetDate]=useState(new Date());
 const[repeatDays,setRepeatDays]=useState<number[]>([]),[repeatUntil,setRepeatUntil]=useState(dateKey(addDays(new Date(),120)));
 const[form,setForm]=useState({title:'',start:'09:00',end:'10:00',category:'집중',note:''});
 const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(weekStart,i)),[weekStart]);
 const weekItems=useMemo(()=>days.flatMap(day=>(itemsByDate[dateKey(day)]??[]).map(item=>({...item,date:day}))).sort((a,b)=>mins(a.start)-mins(b.start)),[days,itemsByDate]);
 useEffect(()=>{const saved=localStorage.getItem('haru-planner-schedules'),savedTasks=localStorage.getItem('haru-planner-tasks');if(saved)setItemsByDate(JSON.parse(saved));else setItemsByDate({[dateKey(new Date())]:starter});setTasks(savedTasks?JSON.parse(savedTasks):starterTasks);setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('haru-planner-schedules',JSON.stringify(itemsByDate))},[itemsByDate,ready]);
 useEffect(()=>{if(ready)localStorage.setItem('haru-planner-tasks',JSON.stringify(tasks))},[tasks,ready]);
 function addTask(e:FormEvent){e.preventDefault();if(!quickTask.trim())return;setTasks(prev=>[...prev,{id:crypto.randomUUID(),title:quickTask.trim(),bucket:'inbox',priority:2}]);setQuickTask('')}
 function patchTask(id:string,patch:Partial<Task>){setTasks(prev=>prev.map(t=>t.id===id?{...t,...patch}:t))}
 function scheduleTask(task:Task){setTargetDate(new Date());setEditing(null);setRepeatDays([]);setRepeatUntil(dateKey(addDays(new Date(),120)));setForm({title:task.title,start:'09:00',end:'10:00',category:'집중',note:''});setModalOpen(true)}
 function openCreate(date:Date,start='09:00'){const end=Math.min(23,Number(start.slice(0,2))+1);setTargetDate(date);setEditing(null);setRepeatDays([]);setRepeatUntil(dateKey(addDays(date,120)));setForm({title:'',start,end:`${pad(end)}:00`,category:'집중',note:''});setModalOpen(true)}
 function openEdit(date:Date,item:Schedule){setTargetDate(date);setEditing(item);setRepeatDays(item.repeat?.weekdays??[]);setRepeatUntil(item.repeat?.until??dateKey(addDays(date,120)));setForm({title:item.title,start:item.start,end:item.end,category:item.category,note:item.note??''});setModalOpen(true)}
 function schedulesForDay(day:Date){const key=dateKey(day),weekday=day.getDay();return Object.entries(itemsByDate).flatMap(([origin,list])=>list.filter(item=>item.repeat?origin<=key&&key<=item.repeat.until&&item.repeat.weekdays.includes(weekday):origin===key))}
 function save(e:FormEvent){e.preventDefault();if(!form.title.trim()||mins(form.end)<=mins(form.start))return;const key=dateKey(targetDate),next:Schedule={id:editing?.id??crypto.randomUUID(),...form,title:form.title.trim(),color:colors[form.category],done:editing?.done??false,repeat:repeatDays.length?{weekdays:repeatDays,until:repeatUntil}:undefined};setItemsByDate(prev=>{if(!editing)return{...prev,[key]:[...(prev[key]??[]),next]};const updated=Object.fromEntries(Object.entries(prev).map(([k,list])=>[k,list.map(i=>i.id===editing.id?next:i)]));return updated});setModalOpen(false)}
 function remove(){if(!editing)return;setItemsByDate(prev=>Object.fromEntries(Object.entries(prev).map(([k,list])=>[k,list.filter(i=>i.id!==editing.id)])));setModalOpen(false)}
 const weekLabel=`${weekStart.getFullYear()}년 ${weekStart.getMonth()+1}월 ${weekStart.getDate()}일 — ${days[6].getMonth()+1}월 ${days[6].getDate()}일`;
 return <main className="week-app">
  <header className="week-topbar"><div className="wordmark">하루</div><div className="week-nav"><button onClick={()=>setWeekStart(addDays(weekStart,-7))} aria-label="이전 주">‹</button><button className="week-today" onClick={()=>setWeekStart(mondayOf(new Date()))}>오늘</button><button onClick={()=>setWeekStart(addDays(weekStart,7))} aria-label="다음 주">›</button></div><div className="week-label">{weekLabel}</div><button className="agenda-toggle" onClick={()=>setAgendaOpen(!agendaOpen)}>{agendaOpen?'목록 숨기기':'할 일 목록'}</button><button className="add-button" onClick={()=>openCreate(new Date())}>＋</button></header>
  <div className={`planner-main ${agendaOpen?'':'panel-hidden'}`}><aside className="task-panel"><div className="task-feed">{(['inbox','week'] as const).map(bucket=><section className="task-section" key={bucket}><header><strong>{bucket==='inbox'?'수집함':'이번 주'}</strong><span>{tasks.filter(t=>t.bucket===bucket&&!t.done).length}</span></header><div>{tasks.filter(t=>t.bucket===bucket).sort((a,b)=>a.priority-b.priority).map(task=><article className={`task-row ${task.done?'done':''}`} key={task.id}><button className="task-check" onClick={()=>patchTask(task.id,{done:!task.done})}>{task.done?'✓':''}</button><div className="task-copy"><strong>{task.title}</strong>{task.dueDate&&<span>{task.dueDate.slice(5).replace('-','/')}</span>}</div><div className="task-actions">{bucket==='inbox'?<button onClick={()=>patchTask(task.id,{bucket:'week'})}>이번 주</button>:<button onClick={()=>patchTask(task.id,{dueDate:dateKey(new Date())})}>오늘</button>}<button onClick={()=>scheduleTask(task)}>시간</button><button aria-label="삭제" onClick={()=>setTasks(prev=>prev.filter(t=>t.id!==task.id))}>×</button></div></article>)}</div></section>)}</div><form className="quick-add" onSubmit={addTask}><textarea rows={1} value={quickTask} onChange={e=>setQuickTask(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder="할 일을 입력하세요"/><button aria-label="보내기">↑</button><small>Enter 전송 · Shift+Enter 줄바꿈</small></form></aside><div className="calendar-stage">
  <section className="week-calendar"><div className="week-days"><div className="time-corner">GMT+9</div>{days.map((day,i)=><button key={dateKey(day)} className={sameDay(day,new Date())?'today-col':''} onClick={()=>openCreate(day)}><span>{weekdays[i]}요일</span><strong>{day.getDate()}</strong></button>)}</div><div className="all-day-row"><div>종일</div>{days.map(day=><div key={dateKey(day)}>{tasks.filter(t=>t.dueDate===dateKey(day)&&!t.done).map(task=><button key={task.id} onClick={()=>patchTask(task.id,{done:true})}><i data-priority={task.priority}/>{task.title}</button>)}</div>)}</div><div className="week-body"><div className="week-times">{hours.map(h=><div key={h}>{h<12?`오전 ${h}시`:h===12?'오후 12시':`오후 ${h-12}시`}</div>)}</div>{days.map(day=><div className={`day-column ${sameDay(day,new Date())?'today-col':''}`} key={dateKey(day)}>{hours.map(h=><button className="week-slot" key={h} onClick={()=>openCreate(day,`${pad(h)}:00`)} aria-label={`${day.getDate()}일 ${h}시 일정 추가`}/>)}{schedulesForDay(day).map(item=>{const top=(mins(item.start)-360)/60*64,height=Math.max(40,(mins(item.end)-mins(item.start))/60*64-4);return <button className={`week-event ${item.done?'done':''}`} key={item.id} style={{top,height,background:backgrounds[item.category]}} onClick={()=>openEdit(day,item)}><strong>{item.title}{item.repeat&&<b className="repeat-mark">↻</b>}</strong><span>{item.start}–{item.end}</span></button>})}</div>)}</div></section></div></div>
  {modalOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModalOpen(false)}><form className="modal" onSubmit={save}><div className="modal-head"><div><p>{targetDate.getMonth()+1}월 {targetDate.getDate()}일 · {editing?'일정 수정':'새 일정'}</p><h2>시간을 계획해볼까요?</h2></div><button type="button" onClick={()=>setModalOpen(false)}>×</button></div><label>일정 이름<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="무엇을 할 예정인가요?" required/></label><div className="time-row"><label>시작<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><span>→</span><label>종료<input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label></div><label>매주 반복 <small className="label-help">선택하지 않으면 한 번만 등록돼요</small><div className="repeat-days">{[1,2,3,4,5,6,0].map((day,i)=><button type="button" key={day} className={repeatDays.includes(day)?'selected':''} onClick={()=>setRepeatDays(prev=>prev.includes(day)?prev.filter(d=>d!==day):[...prev,day])}>{weekdays[i]}</button>)}</div></label>{repeatDays.length>0&&<label>반복 종료일<input type="date" min={dateKey(targetDate)} value={repeatUntil} onChange={e=>setRepeatUntil(e.target.value)}/></label>}<label>분류<div className="category-row">{Object.keys(colors).map(cat=><button key={cat} type="button" className={form.category===cat?'selected':''} style={{'--cat':colors[cat]} as React.CSSProperties} onClick={()=>setForm({...form,category:cat})}>{cat}</button>)}</div></label><label>메모<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="세부 내용을 적어두세요 (선택)"/></label>{mins(form.end)<=mins(form.start)&&<p className="form-error">종료 시간은 시작 시간보다 늦어야 해요.</p>}<div className="modal-actions">{editing&&<button type="button" className="delete" onClick={remove}>{editing.repeat?'반복 일정 삭제':'삭제'}</button>}<button type="button" className="cancel" onClick={()=>setModalOpen(false)}>취소</button><button type="submit" className="save">{editing?'수정 완료':'일정 추가'}</button></div></form></div>}
 </main>
}
